### PR TITLE
Fix merging array elements

### PR DESCRIPTION
**Pull request by urso**
- add flags test overwriting array elements + creating empty array entries
- fix initializing empty array elements to cfgNil
- fix array elements from other configurations not being merged

### CODE REVIEW

**Comment by urso** [comment]
Resolves #58 and #59

**Comment by ruflin** [comment]
@urso Golang 1.6 does not seem to be happy with this change?

**Comment by ruflin** [comment]
LGTM

**Comment by urso** [comment]
@ruflin fixed

**Pull request merged**
